# Generated by Django 5.2.3 on 2025-06-22 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=32)),
                ('data_structures', models.CharField(max_length=512)),
                ('design_paradigm', models.CharField(max_length=32)),
                ('generality', models.CharField(max_length=32)),
                ('temporal_complexity', models.CharField(max_length=32)),
                ('spatial_complexity', models.CharField(max_length=32)),
                ('solution_kind', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_public', models.CharField(max_length=32)),
                ('name_user', models.CharField(max_length=32, unique=True)),
                ('name_email', models.CharField(max_length=64, unique=True)),
                ('name_password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='inactive', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
