# Generated by Django 5.2.3 on 2025-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiki_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
