# Generated by Django 5.2.3 on 2025-07-14 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiki_site', '0002_alter_jogador_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receivers', models.ManyToManyField(related_name='received_messages', to='saiki_site.jogador')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='saiki_site.jogador')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.IntegerField(default=0)),
                ('number_of_messages', models.IntegerField(default=0)),
                ('participants', models.ManyToManyField(related_name='chats', to='saiki_site.jogador')),
                ('messages', models.ManyToManyField(related_name='chats', to='saiki_site.message')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=64, unique=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('session_time', models.DurationField(blank=True, null=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saiki_site.chat')),
                ('players', models.ManyToManyField(related_name='sessions', to='saiki_site.jogador')),
                ('root_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_sessions', to='saiki_site.jogador')),
            ],
        ),
    ]
