# Generated by Django 5.2.3 on 2025-07-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiki_site', '0003_alter_jogador_options_message_chat_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='session',
            name='active_players',
            field=models.ManyToManyField(blank=True, related_name='active_sessions', to='saiki_site.jogador'),
        ),
        migrations.AlterField(
            model_name='session',
            name='data_inicio',
            field=models.DateTimeField(editable=False),
        ),
    ]
