# Generated by Django 5.2.3 on 2025-07-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiki_site', '0004_alter_session_options_session_active_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
